---
title: "Moive Recommendation"
output: html_notebook
---

First step, import the file and clean the data 

```{r, echo=FALSE}
#install necessary packages and load libraries
if (!require("tidyverse")) install.packages("tidyverse");library(tidyverse)
if (!require("jsonlite")) install.packages("jsonlite");library(jsonlite)
if (!require("fastDummies")) install.packages("fastDummies");library(fastDummies)
if (!require("class")) install.packages("class");library(class)
if (!require("recommenderlab")) install.packages("recommenderlab");library(recommenderlab)
if (!require("tm")) install.packages("tm");library(tm)
if (!require("text2vec")) install.packages("text2vec");library(text2vec)
```


```{r}
#load data
movies <- read_csv("./data/tmdb_5000_movies.csv")
credits <- read_csv("./data/tmdb_5000_credits.csv")
```


```{r}
# gather all genres under one movie 
movie_with_tag <- movies %>% filter(nchar(genres) > 2) %>% mutate(genres = lapply(genres, fromJSON)) %>% unnest(genres) %>% select(id, title, genres = name)

# do the same thing to cast members per movie 
credits_cast <- credits %>% select(-crew) %>% filter(nchar(cast) >2) %>% mutate(cast=lapply(cast,fromJSON)) %>% unnest(cast) %>% select(movie_id,title,cast=name) %>% mutate(id=movie_id)%>%mutate(movie_id=NULL) %>% mutate(casts = str_replace_all(cast, " ", "")) %>% select(id, title, cast = casts) %>% group_by(id, title) %>% mutate(cast = paste0(cast, collapse = " ")) %>% distinct()



movie_bag <- movies %>% filter(nchar(genres) > 2) %>% mutate(genres = lapply(genres, fromJSON)) %>% unnest(genres) %>% select(id,title,genres=name,overview) %>% group_by(id,title) %>% mutate(genres = paste0(genres, collapse =" ")) %>% distinct()

movie_bag2 <- inner_join(credits_cast,movie_bag,by="id")%>%select(id,title.x,cast,genres,overview)

# then repeat it for keywords per movie 
movie_with_keywords <- movies %>% filter(nchar(keywords) > 2) %>% mutate(keywords = lapply(keywords, fromJSON)) %>% unnest(keywords) %>% select(id, title, keywords = name)%>% group_by(id,title) %>% mutate(keywords=paste0(keywords, collapse=" ")) %>% distinct()

# repeat it for directors per movie 
movie_with_directors <- credits %>% select(-cast) %>% filter(nchar(crew) >2) %>% mutate(directors = lapply(crew, fromJSON)) %>% unnest(directors)%>% select(movie_id,title,job,directors=name) %>% filter(job == "Director")%>%mutate(id=movie_id)%>%mutate(movie_id=NULL)%>% mutate(director = str_replace_all(directors, " ", "")) %>% select(id, title, directors = director) %>% group_by(id, title) %>% mutate(directors = paste0(directors, collapse = " ")) %>% distinct()

# intergrate genres, cast and keywords together into a tibble and perform some preprocessing(transform words into lower case, remove punctuation)
movie_all <- inner_join(movie_with_keywords,movie_bag2, by="id") %>% select(-title.x) %>% mutate(overview=tolower(overview))%>%mutate(overview=removePunctuation(overview)) %>% mutate(keywords=tolower(keywords)) %>% mutate(cast=tolower(cast)) %>% mutate(genres=tolower(genres))

movie_a <- inner_join(movie_all,movie_with_directors, by=c("id","title"))%>% mutate(directors=tolower(directors))

# create a column with name "bag of words" and put genres, actors, keywords and overview into it to construct bag of words for each film
movie_words <- movie_a %>% group_by(title, id) %>% mutate(bag_of_words = paste(genres, keywords, cast, overview, directors, sep=" ",collapse=" "))

movie_full <- movie_with_tag %>% inner_join(movie_with_keywords, by = "id")

movie_full %>% group_by(keywords) %>% count() %>% arrange(desc(n))

movie_full %>% group_by(genres) %>% count() %>% arrange(desc(n))

#create document matrix and compute tf-idf cosine similarity 
it <- itoken(movie_words$bag_of_words,word_tokenizer)
v <- create_vocabulary(it)
vectorizer <- vocab_vectorizer(v)
dtm <- create_dtm(it,vectorizer)
model_tf <- TfIdf$new()
dtm_tfidf = model_tf$fit_transform(dtm)
cos_sim = sim2(x = dtm_tfidf, method = "cosine", norm = "l2")

#build the function that takes a movie name as input and returns 5 recommended movies
rec <- function(title_input,c = cos_sim){
  recommend_movies <- rep(NA,10)
  #get index that matches the input movie title
  idx <- which(movie_words$title==title_input)
  top_5 <- order(cos_sim[idx,],decreasing=T)[2:11]
  for (i in 1:10){
    recommend_movies[i] <- movie_words[top_5[i],]$title
  }
  return(recommend_movies)
}

#test one movie
rec("Tangled")
```



```{r}

movie_with_tag_dummy <- movie_with_tag %>% dummy_cols("genres") 

movie_with_tag_dummy <- movie_with_tag_dummy %>% select(-genres) %>% group_by(id, title) %>% summarize_all(sum) 


movie_with_keywords_dummy <- movie_with_keywords %>% dummy_cols("keywords")

movie_with_keywords_dummy <- movie_with_keywords_dummy %>% select(-keywords) 

movie_with_keywords_dummy2 <- movie_with_keywords_dummy

colnames(movie_with_keywords_dummy2) <- enc2native(colnames(movie_with_keywords_dummy2))

movie_with_keywords_dummy2 <- movie_with_keywords_dummy2 %>% group_by(id, title) %>% summarize_all(sum)


movie_dummy_all <- movie_with_tag_dummy %>% inner_join(movie_with_keywords_dummy2, by = c("id", "title"))



```


```{r}
movie_dummy_all_train <- movie_dummy_all %>% select(-id, -title)


```

```{r warning=F}
library(rvest)
library(purrr)
url <- lapply(paste0("https://www.themoviedb.org/movie?page=",1:993),
function(url){
 pr <- url %>% read_html()%>%html_nodes("[class='poster lazyload fade']")
 name <- pr %>% html_attr('alt')
 imgs <- pr %>% html_attr('data-src')
 c(name, imgs)
})

list_lost_pic <- NA
for (i in 1:993){
list_lost_pic[i] <- length(url[[i]])<40
}

num <- which(list_lost_pic)
num2 <- seq(1:993)
num3 <- setdiff(num2,num)
num3 <- num3[! num3 %in% 1:2]
d <- data.frame(matrix(unlist(url[[1]]), nrow=20, ncol=2))
q <- data.frame(matrix(unlist(url[[2]]),nrow=20,ncol=2))
dat <- rbind(d,q)
for (i in num3){
q <- data.frame(matrix(unlist(url[[i]]), nrow=20, ncol=2))
dat <- rbind(dat,q);
}

write_csv(dat,path="movie_image2.csv")
 
movie_img <- read_csv("movie_image2.csv")

library(data.table)
m <- fread("movie_image2.csv",encoding="UTF-8",header=T)
m$X1 <- str_replace_all(m$X1,pattern="[[:punct:]]|[^[:ascii:]]", "")
n <- nrow(movie_img)
a <- rep(NA,n)
b <- rep(NA,n)
for (i in 1:n){
 a[i] <- m[i,2]
 b[i] <- m[i,1]
 download.file(paste0(a[i]),paste("./img/",b[i],".JPEG",sep=""),mode="wb")
}
```
